[package]
name = "albion-island-balancer"
version = "0.1.0"
authors = ["Christian Smith <smith.christian.william@gmail.com>"]
edition = "2021"

[dependencies]
linprog = "0.3.1"
clap = { version = "4.5.4", features = ["derive"] }

