use linprog::{
    Model,
    Objective,
    Summand,
    Operator,
    Var
};

use crate::{constants::*, types::Product, ModelContext};


pub fn optimize_plots(context: ModelContext) -> Model {
    let mut model = Model::new("Plots", Objective::Max);
    
    let plots_brecilien = model.reg_var(0.0);
    let plots_bridgewatch = model.reg_var(0.0);
    let plots_caerleon = model.reg_var(0.0);
    let plots_fort_sterling = model.reg_var(0.0);
    let plots_lymhurst = model.reg_var(0.0);
    let plots_martlock = model.reg_var(0.0);
    let plots_thetford = model.reg_var(0.0);
    let herb_gardens_brecilien = model.reg_var(0.0);
    let farms_brecilien = model.reg_var(0.0);
    let pastures_brecilien = model.reg_var(0.0);
    let herb_gardens_bridgewatch = model.reg_var(0.0);
    let farms_bridgewatch = model.reg_var(0.0);
    let pastures_bridgewatch = model.reg_var(0.0);
    let herb_gardens_caerleon = model.reg_var(0.0);
    let farms_caerleon = model.reg_var(0.0);
    let pastures_caerleon = model.reg_var(0.0);
    let herb_gardens_fort_sterling = model.reg_var(0.0);
    let farms_fort_sterling = model.reg_var(0.0);
    let pastures_fort_sterling = model.reg_var(0.0);
    let herb_gardens_lymhurst = model.reg_var(0.0);
    let farms_lymhurst = model.reg_var(0.0);
    let pastures_lymhurst = model.reg_var(0.0);
    let herb_gardens_martlock = model.reg_var(0.0);
    let farms_martlock = model.reg_var(0.0);
    let pastures_martlock = model.reg_var(0.0);
    let herb_gardens_thetford = model.reg_var(0.0);
    let farms_thetford = model.reg_var(0.0);
    let pastures_thetford = model.reg_var(0.0);
    let herb_garden_tiles_brecilien = model.reg_var(0.0);
    let farm_tiles_brecilien = model.reg_var(0.0);
    let pasture_tiles_brecilien = model.reg_var(0.0);
    let herb_garden_tiles_bridgewatch = model.reg_var(0.0);
    let farm_tiles_bridgewatch = model.reg_var(0.0);
    let pasture_tiles_bridgewatch = model.reg_var(0.0);
    let herb_garden_tiles_caerleon = model.reg_var(0.0);
    let farm_tiles_caerleon = model.reg_var(0.0);
    let pasture_tiles_caerleon = model.reg_var(0.0);
    let herb_garden_tiles_fort_sterling = model.reg_var(0.0);
    let farm_tiles_fort_sterling = model.reg_var(0.0);
    let pasture_tiles_fort_sterling = model.reg_var(0.0);
    let herb_garden_tiles_lymhurst = model.reg_var(0.0);
    let farm_tiles_lymhurst = model.reg_var(0.0);
    let pasture_tiles_lymhurst = model.reg_var(0.0);
    let herb_garden_tiles_martlock = model.reg_var(0.0);
    let farm_tiles_martlock = model.reg_var(0.0);
    let pasture_tiles_martlock = model.reg_var(0.0);
    let herb_garden_tiles_thetford = model.reg_var(0.0);
    let farm_tiles_thetford = model.reg_var(0.0);
    let pasture_tiles_thetford = model.reg_var(0.0);
    let agaric_tiles_brecilien = model.reg_var(0.0);
    let comfrey_tiles_brecilien = model.reg_var(0.0);
    let burdock_tiles_brecilien = model.reg_var(0.0);
    let teasel_tiles_brecilien = model.reg_var(0.0);
    let foxglove_tiles_brecilien = model.reg_var(0.0);
    let muellin_tiles_brecilien = model.reg_var(0.0);
    let yarrow_tiles_brecilien = model.reg_var(0.0);
    let carrot_tiles_brecilien = model.reg_var(0.0);
    let bean_tiles_brecilien = model.reg_var(0.0);
    let wheat_tiles_brecilien = model.reg_var(0.0);
    let turnip_tiles_brecilien = model.reg_var(0.0);
    let cabbage_tiles_brecilien = model.reg_var(0.0);
    let potato_tiles_brecilien = model.reg_var(0.0);
    let corn_tiles_brecilien = model.reg_var(0.0);
    let pumpkin_tiles_brecilien = model.reg_var(0.0);
    let baby_chicken_tiles_brecilien = model.reg_var(0.0);
    let kid_tiles_brecilien = model.reg_var(0.0);
    let gosling_tiles_brecilien = model.reg_var(0.0);
    let lamb_tiles_brecilien = model.reg_var(0.0);
    let piglet_tiles_brecilien = model.reg_var(0.0);
    let calf_tiles_brecilien = model.reg_var(0.0);
    let chicken_tiles_brecilien = model.reg_var(0.0);
    let goat_tiles_brecilien = model.reg_var(0.0);
    let goose_tiles_brecilien = model.reg_var(0.0);
    let sheep_tiles_brecilien = model.reg_var(0.0);
    let pig_tiles_brecilien = model.reg_var(0.0);
    let cow_tiles_brecilien = model.reg_var(0.0);
    let agaric_tiles_bridgewatch = model.reg_var(0.0);
    let comfrey_tiles_bridgewatch = model.reg_var(0.0);
    let burdock_tiles_bridgewatch = model.reg_var(0.0);
    let teasel_tiles_bridgewatch = model.reg_var(0.0);
    let foxglove_tiles_bridgewatch = model.reg_var(0.0);
    let muellin_tiles_bridgewatch = model.reg_var(0.0);
    let yarrow_tiles_bridgewatch = model.reg_var(0.0);
    let carrot_tiles_bridgewatch = model.reg_var(0.0);
    let bean_tiles_bridgewatch = model.reg_var(0.0);
    let wheat_tiles_bridgewatch = model.reg_var(0.0);
    let turnip_tiles_bridgewatch = model.reg_var(0.0);
    let cabbage_tiles_bridgewatch = model.reg_var(0.0);
    let potato_tiles_bridgewatch = model.reg_var(0.0);
    let corn_tiles_bridgewatch = model.reg_var(0.0);
    let pumpkin_tiles_bridgewatch = model.reg_var(0.0);
    let baby_chicken_tiles_bridgewatch = model.reg_var(0.0);
    let kid_tiles_bridgewatch = model.reg_var(0.0);
    let gosling_tiles_bridgewatch = model.reg_var(0.0);
    let lamb_tiles_bridgewatch = model.reg_var(0.0);
    let piglet_tiles_bridgewatch = model.reg_var(0.0);
    let calf_tiles_bridgewatch = model.reg_var(0.0);
    let chicken_tiles_bridgewatch = model.reg_var(0.0);
    let goat_tiles_bridgewatch = model.reg_var(0.0);
    let goose_tiles_bridgewatch = model.reg_var(0.0);
    let sheep_tiles_bridgewatch = model.reg_var(0.0);
    let pig_tiles_bridgewatch = model.reg_var(0.0);
    let cow_tiles_bridgewatch = model.reg_var(0.0);
    let agaric_tiles_caerleon = model.reg_var(0.0);
    let comfrey_tiles_caerleon = model.reg_var(0.0);
    let burdock_tiles_caerleon = model.reg_var(0.0);
    let teasel_tiles_caerleon = model.reg_var(0.0);
    let foxglove_tiles_caerleon = model.reg_var(0.0);
    let muellin_tiles_caerleon = model.reg_var(0.0);
    let yarrow_tiles_caerleon = model.reg_var(0.0);
    let carrot_tiles_caerleon = model.reg_var(0.0);
    let bean_tiles_caerleon = model.reg_var(0.0);
    let wheat_tiles_caerleon = model.reg_var(0.0);
    let turnip_tiles_caerleon = model.reg_var(0.0);
    let cabbage_tiles_caerleon = model.reg_var(0.0);
    let potato_tiles_caerleon = model.reg_var(0.0);
    let corn_tiles_caerleon = model.reg_var(0.0);
    let pumpkin_tiles_caerleon = model.reg_var(0.0);
    let baby_chicken_tiles_caerleon = model.reg_var(0.0);
    let kid_tiles_caerleon = model.reg_var(0.0);
    let gosling_tiles_caerleon = model.reg_var(0.0);
    let lamb_tiles_caerleon = model.reg_var(0.0);
    let piglet_tiles_caerleon = model.reg_var(0.0);
    let calf_tiles_caerleon = model.reg_var(0.0);
    let chicken_tiles_caerleon = model.reg_var(0.0);
    let goat_tiles_caerleon = model.reg_var(0.0);
    let goose_tiles_caerleon = model.reg_var(0.0);
    let sheep_tiles_caerleon = model.reg_var(0.0);
    let pig_tiles_caerleon = model.reg_var(0.0);
    let cow_tiles_caerleon = model.reg_var(0.0);
    let agaric_tiles_fort_sterling = model.reg_var(0.0);
    let comfrey_tiles_fort_sterling = model.reg_var(0.0);
    let burdock_tiles_fort_sterling = model.reg_var(0.0);
    let teasel_tiles_fort_sterling = model.reg_var(0.0);
    let foxglove_tiles_fort_sterling = model.reg_var(0.0);
    let muellin_tiles_fort_sterling = model.reg_var(0.0);
    let yarrow_tiles_fort_sterling = model.reg_var(0.0);
    let carrot_tiles_fort_sterling = model.reg_var(0.0);
    let bean_tiles_fort_sterling = model.reg_var(0.0);
    let wheat_tiles_fort_sterling = model.reg_var(0.0);
    let turnip_tiles_fort_sterling = model.reg_var(0.0);
    let cabbage_tiles_fort_sterling = model.reg_var(0.0);
    let potato_tiles_fort_sterling = model.reg_var(0.0);
    let corn_tiles_fort_sterling = model.reg_var(0.0);
    let pumpkin_tiles_fort_sterling = model.reg_var(0.0);
    let baby_chicken_tiles_fort_sterling = model.reg_var(0.0);
    let kid_tiles_fort_sterling = model.reg_var(0.0);
    let gosling_tiles_fort_sterling = model.reg_var(0.0);
    let lamb_tiles_fort_sterling = model.reg_var(0.0);
    let piglet_tiles_fort_sterling = model.reg_var(0.0);
    let calf_tiles_fort_sterling = model.reg_var(0.0);
    let chicken_tiles_fort_sterling = model.reg_var(0.0);
    let goat_tiles_fort_sterling = model.reg_var(0.0);
    let goose_tiles_fort_sterling = model.reg_var(0.0);
    let sheep_tiles_fort_sterling = model.reg_var(0.0);
    let pig_tiles_fort_sterling = model.reg_var(0.0);
    let cow_tiles_fort_sterling = model.reg_var(0.0);
    let agaric_tiles_lymhurst = model.reg_var(0.0);
    let comfrey_tiles_lymhurst = model.reg_var(0.0);
    let burdock_tiles_lymhurst = model.reg_var(0.0);
    let teasel_tiles_lymhurst = model.reg_var(0.0);
    let foxglove_tiles_lymhurst = model.reg_var(0.0);
    let muellin_tiles_lymhurst = model.reg_var(0.0);
    let yarrow_tiles_lymhurst = model.reg_var(0.0);
    let carrot_tiles_lymhurst = model.reg_var(0.0);
    let bean_tiles_lymhurst = model.reg_var(0.0);
    let wheat_tiles_lymhurst = model.reg_var(0.0);
    let turnip_tiles_lymhurst = model.reg_var(0.0);
    let cabbage_tiles_lymhurst = model.reg_var(0.0);
    let potato_tiles_lymhurst = model.reg_var(0.0);
    let corn_tiles_lymhurst = model.reg_var(0.0);
    let pumpkin_tiles_lymhurst = model.reg_var(0.0);
    let baby_chicken_tiles_lymhurst = model.reg_var(0.0);
    let kid_tiles_lymhurst = model.reg_var(0.0);
    let gosling_tiles_lymhurst = model.reg_var(0.0);
    let lamb_tiles_lymhurst = model.reg_var(0.0);
    let piglet_tiles_lymhurst = model.reg_var(0.0);
    let calf_tiles_lymhurst = model.reg_var(0.0);
    let chicken_tiles_lymhurst = model.reg_var(0.0);
    let goat_tiles_lymhurst = model.reg_var(0.0);
    let goose_tiles_lymhurst = model.reg_var(0.0);
    let sheep_tiles_lymhurst = model.reg_var(0.0);
    let pig_tiles_lymhurst = model.reg_var(0.0);
    let cow_tiles_lymhurst = model.reg_var(0.0);
    let agaric_tiles_martlock = model.reg_var(0.0);
    let comfrey_tiles_martlock = model.reg_var(0.0);
    let burdock_tiles_martlock = model.reg_var(0.0);
    let teasel_tiles_martlock = model.reg_var(0.0);
    let foxglove_tiles_martlock = model.reg_var(0.0);
    let muellin_tiles_martlock = model.reg_var(0.0);
    let yarrow_tiles_martlock = model.reg_var(0.0);
    let carrot_tiles_martlock = model.reg_var(0.0);
    let bean_tiles_martlock = model.reg_var(0.0);
    let wheat_tiles_martlock = model.reg_var(0.0);
    let turnip_tiles_martlock = model.reg_var(0.0);
    let cabbage_tiles_martlock = model.reg_var(0.0);
    let potato_tiles_martlock = model.reg_var(0.0);
    let corn_tiles_martlock = model.reg_var(0.0);
    let pumpkin_tiles_martlock = model.reg_var(0.0);
    let baby_chicken_tiles_martlock = model.reg_var(0.0);
    let kid_tiles_martlock = model.reg_var(0.0);
    let gosling_tiles_martlock = model.reg_var(0.0);
    let lamb_tiles_martlock = model.reg_var(0.0);
    let piglet_tiles_martlock = model.reg_var(0.0);
    let calf_tiles_martlock = model.reg_var(0.0);
    let chicken_tiles_martlock = model.reg_var(0.0);
    let goat_tiles_martlock = model.reg_var(0.0);
    let goose_tiles_martlock = model.reg_var(0.0);
    let sheep_tiles_martlock = model.reg_var(0.0);
    let pig_tiles_martlock = model.reg_var(0.0);
    let cow_tiles_martlock = model.reg_var(0.0);
    let agaric_tiles_thetford = model.reg_var(0.0);
    let comfrey_tiles_thetford = model.reg_var(0.0);
    let burdock_tiles_thetford = model.reg_var(0.0);
    let teasel_tiles_thetford = model.reg_var(0.0);
    let foxglove_tiles_thetford = model.reg_var(0.0);
    let muellin_tiles_thetford = model.reg_var(0.0);
    let yarrow_tiles_thetford = model.reg_var(0.0);
    let carrot_tiles_thetford = model.reg_var(0.0);
    let bean_tiles_thetford = model.reg_var(0.0);
    let wheat_tiles_thetford = model.reg_var(0.0);
    let turnip_tiles_thetford = model.reg_var(0.0);
    let cabbage_tiles_thetford = model.reg_var(0.0);
    let potato_tiles_thetford = model.reg_var(0.0);
    let corn_tiles_thetford = model.reg_var(0.0);
    let pumpkin_tiles_thetford = model.reg_var(0.0);
    let baby_chicken_tiles_thetford = model.reg_var(0.0);
    let kid_tiles_thetford = model.reg_var(0.0);
    let gosling_tiles_thetford = model.reg_var(0.0);
    let lamb_tiles_thetford = model.reg_var(0.0);
    let piglet_tiles_thetford = model.reg_var(0.0);
    let calf_tiles_thetford = model.reg_var(0.0);
    let chicken_tiles_thetford = model.reg_var(0.0);
    let goat_tiles_thetford = model.reg_var(0.0);
    let goose_tiles_thetford = model.reg_var(0.0);
    let sheep_tiles_thetford = model.reg_var(0.0);
    let pig_tiles_thetford = model.reg_var(0.0);
    let cow_tiles_thetford = model.reg_var(0.0);
    let agaric_herbs = model.reg_var(0.0);
    let comfrey_herbs = model.reg_var(0.0);
    let burdock_herbs = model.reg_var(0.0);
    let teasel_herbs = model.reg_var(0.0);
    let foxglove_herbs = model.reg_var(0.0);
    let muellin_herbs = model.reg_var(0.0);
    let yarrow_herbs = model.reg_var(0.0);
    let carrot_crops = model.reg_var(0.0);
    let bean_crops = model.reg_var(0.0);
    let wheat_crops = model.reg_var(0.0);
    let turnip_crops = model.reg_var(0.0);
    let cabbage_crops = model.reg_var(0.0);
    let potato_crops = model.reg_var(0.0);
    let corn_crops = model.reg_var(0.0);
    let pumpkin_crops = model.reg_var(0.0);
    let hen_eggs = model.reg_var(0.0);
    let goats_milk = model.reg_var(0.0);
    let goose_eggs = model.reg_var(0.0);
    let sheeps_milk = model.reg_var(0.0);
    let cows_milk = model.reg_var(0.0);
    let raw_chicken = model.reg_var(0.0);
    let raw_goat = model.reg_var(0.0);
    let raw_goose = model.reg_var(0.0);
    let raw_mutton = model.reg_var(0.0);
    let raw_pork = model.reg_var(0.0);
    let raw_beef = model.reg_var(0.0);
    let minor_energy_potion = model.reg_var(if context.target == Product::MinorEnergyPotion { 1.0 } else { if context.target == Product::MinorHealingPotion { 1.0 } else { 0.0 } });
    let minor_healing_potion = model.reg_var(if context.target == Product::MinorHealingPotion { 1.0 } else { 0.0 });
    let minor_gigantify_potion = model.reg_var(if context.target == Product::MinorGigantifyPotion { 1.0 } else { 0.0 });
    let minor_resistance_potion = model.reg_var(if context.target == Product::MinorResistancePotion { 1.0 } else { 0.0 });
    let minor_sticky_potion = model.reg_var(if context.target == Product::MinorStickyPotion { 1.0 } else { 0.0 });
    let minor_poison_potion = model.reg_var(if context.target == Product::MinorPoisonPotion { 1.0 } else { 0.0 });
    let energy_potion = model.reg_var(if context.target == Product::EnergyPotion { 1.0 } else { 0.0 });
    let healing_potion = model.reg_var(if context.target == Product::HealingPotion { 1.0 } else { 0.0 });
    let gigantify_potion = model.reg_var(if context.target == Product::GigantifyPotion { 1.0 } else { 0.0 });
    let resistance_potion = model.reg_var(if context.target == Product::ResistancePotion { 1.0 } else { 0.0 });
    let sticky_potion = model.reg_var(if context.target == Product::StickyPotion { 1.0 } else { 0.0 });
    let poison_potion = model.reg_var(if context.target == Product::PoisonPotion { 1.0 } else { 0.0 });
    let major_energy_potion = model.reg_var(if context.target == Product::MajorEnergyPotion { 1.0 } else { 0.0 });
    let major_healing_potion = model.reg_var(if context.target == Product::MajorHealingPotion { 1.0 } else { 0.0 });
    let major_gigantify_potion = model.reg_var(if context.target == Product::MajorGigantifyPotion { 1.0 } else { 0.0 });
    let major_resistance_potion = model.reg_var(if context.target == Product::MajorResistancePotion { 1.0 } else { 0.0 });
    let major_sticky_potion = model.reg_var(if context.target == Product::MajorStickyPotion { 1.0 } else { 0.0 });
    let major_poison_potion = model.reg_var(if context.target == Product::MajorPoisonPotion { 1.0 } else { 0.0 });
    let invisibility_potion = model.reg_var(if context.target == Product::InvisibilityPotion { 1.0 } else { 0.0 });
    let chicken_omelette = model.reg_var(if context.target == Product::ChickenOmelette { 1.0 } else { 0.0 });
    let goose_omelette = model.reg_var(if context.target == Product::GooseOmelette { 1.0 } else { 0.0 });
    let pork_omelette = model.reg_var(if context.target == Product::PorkOmelette { 1.0 } else { 0.0 });
    let bean_salad = model.reg_var(if context.target == Product::BeanSalad { 1.0 } else { 0.0 });
    let turnip_salad = model.reg_var(if context.target == Product::TurnipSalad { 1.0 } else { 0.0 });
    let potato_salad = model.reg_var(if context.target == Product::PotatoSalad { 1.0 } else { 0.0 });
    let goat_sandwich = model.reg_var(if context.target == Product::GoatSandwich { 1.0 } else { 0.0 });
    let mutton_sandwich = model.reg_var(if context.target == Product::MuttonSandwich { 1.0 } else { 0.0 });
    let beef_sandwich = model.reg_var(if context.target == Product::BeefSandwich { 1.0 } else { 0.0 });
    let carrot_soup = model.reg_var(if context.target == Product::CarrotSoup { 1.0 } else { 0.0 });
    let wheat_soup = model.reg_var(if context.target == Product::WheatSoup { 1.0 } else { 0.0 });
    let cabbage_soup = model.reg_var(if context.target == Product::CabbageSoup { 1.0 } else { 0.0 });
    let goat_stew = model.reg_var(if context.target == Product::GoatStew { 1.0 } else { 0.0 });
    let mutton_stew = model.reg_var(if context.target == Product::MuttonStew { 1.0 } else { 0.0 });
    let beef_stew = model.reg_var(if context.target == Product::BeefStew { 1.0 } else { 0.0 });
    let roast_chicken = model.reg_var(if context.target == Product::RoastChicken { 1.0 } else { 0.0 });
    let roast_goose = model.reg_var(if context.target == Product::RoastGoose { 1.0 } else { 0.0 });
    let roast_pork = model.reg_var(if context.target == Product::RoastPork { 1.0 } else { 0.0 });
    

    let mut vars: Vec<Var> = vec![];
    vars.push(model.reg_var(2.0));
    model.reg_constr(vec![Summand(1.0, &vars[0])], Operator::Le, 10.0);
    
    model.optimize();
    model
}